### ISSUE TITLE
[chainweb-node-client] /send should first do a /local preflight call

### ISSUE THREAD

**Issue by Randynamic** [kadena-community/kadena.js#103]
**Is your feature request related to a problem? Please describe.**
It's a best practice to pre-flight every single command with /local  (with the caveat that some failures are still impossible to trigger in local)

**Describe the solution you'd like**
When calling `/send` first call `/local` when succeeded actually call `/send`

https://github.com/kadena-community/kadena.js/blob/master/packages/libs/chainweb-node-client/src/pact/send.ts#L41

**Comment by alber70g** [comment]
We could add a flag that allows a `send()` call to validated.

Usage example:

```ts
try {
  await new PactCommand().send(apiHost, { local: true }); // promise throws LocalError when local fails
} catch (err) {
  if (err instanceof LocalError) {
    // do something specific for a /local error
  }
  // do something else with other errors
}
```
