### ISSUE TITLE
"n lts" installs v18. suggest "n 16" or similar instead

### ISSUE THREAD

**Issue by friday-mydae** [kadena-community/kadena.js#141]
### What article is affected?

https://github.com/kadena-community/kadena.js#installing-prerequisites

### What part(s) of the article would you like to see updated?

Requirements
node > LTS (node 16, as 18 isn't yet LTS)

install node
n lts // installs 18

suggest "n 16" instead

**Comment by alber70g** [comment]
Added in https://github.com/kadena-community/kadena.js/commit/f75e8291c345913d907ee366f9f08697dff8acbc#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by ash-vd** [comment]
Node 18 is LTS since October '22, 16 is Maintenance since then: https://github.com/nodejs/Release
