### ISSUE TITLE
Document the class PactCommand

### ISSUE THREAD

**Issue by CryptoPascal31** [kadena-community/kadena.js#161]
Some users like me would like to use the client library without using "contract parsing" nor "template based".

I've found out that the PactCommand class was very convenient to use directly.  

I'm pretty sure, that most devs (like me), prefer to use PactCommand, and writing a couple of Pact lines, in their JS source,
than using an heavy infrastructure of contract downloading/parsing... or writing templates.

Why not describing this class usage in the README.md ?

**Comment by alber70g** [comment]
Yes we meant to do this, but time constraints have had us delaying this.

Another thing on our mind is to separate the code generation and the PactCommand builder utility. We'd rather have that done together with the docs you mention.

Feel free to add submit a PR to document this behaviour.

**Comment by alber70g** [comment]
Mergin #167 now, so this will be added.

Separating code generation and PactCommand builder is still open. Will close this issue in favor of #172

**Comment by alber70g** [comment]
Merging #167 now, so this will be added.

Separating code generation and PactCommand builder is still open. Will close this issue in favor of #172
