### ISSUE TITLE
README Getting Started Feels incomplete

### ISSUE THREAD

**Issue by Luzzotica** [kadena-community/kadena.js#163]
### What article is affected?

https://github.com/kadena-community/kadena.js/blob/master/README.md

### What part(s) of the article would you like to see updated?

The Getting Started portion feels incomplete to me.

I tried running `rush add -p @kadena/types` but I get this error:

```bash
ERROR: The "rush add" command must be invoked under a project folder that is registered in rush.json unless the --all is used
```

So, my files have errors in them, they can't import the @kadena/types or other things.

I would recommend cloning the repo, deleting rush from the global npm area, and starting from scratch for the setup. I'm certain there are more steps that I am unaware of.
I have also NEVER used rush. I tried reading the getting started with rush, but that wasn't helpful.

**Comment by alber70g** [comment]
Take a look at: https://rushjs.io/pages/developer/modifying_package_json/#rush-add

When you want to add the package `@kadena/types` to a projects dependencies in `package.json`, you need to be in a directory that Rush knows as a project (See also [Add a project to the repo](https://rushjs.io/pages/maintainer/add_to_repo/)). Hence the error `command must be invoked under a project folder that is registered in rush.json`. 

You probably haven't `cd`ed into the directory in which package you want to add the dependency, **or** the package isn't registered in `rush.json`.

I'm closing this issue for now, as I think most of these things are well documented in the rush docs. If you're still missing something feel free to comment here.
