### ISSUE TITLE
Updating the README

### ISSUE THREAD

**Issue by Luzzotica** [kadena-community/kadena.js#170]
### What article is affected?

The README.

### What part(s) of the article would you like to see updated?

To me, the purpose of the README is twofold:

1. Provide people who want to use the repo the information they need to get started.
2. Build the path and documentation that allows people to contribute to the repo itself.

To facilitate the above, I feel that the following pieces must be in place:

1. A clear description of the repo and its purpose.
2. A clear definition on everything the repo contains. I've made improvements already in #168 and @alber70g suggested doing something like [this](https://github.com/microsoft/rushstack/blob/main/README.md), which I am 100% on board with.
3. Step by step instructions on how to setup the repo so that others can easily contribute. I personally feel like this shouldn't be so complex that you need a separate .md file called CONTRIBUTING. Just put it all in the readme. The CONTRIBUTING file can be used to list off the current things that are being developed perhaps, but HOW you contribute should just be in the README.

Max Howell, the creator of Homebrew told me "I build the way to contribute to the tool, into the tool itself".
If we can make it so easy for people to request or suggest changes to KadenaJS that they almost have no excuse not to, we will have succeeded in building a tool that can be run by the community of people who use it.

I'm open to other things you guys feel a repo needs, these 3 things are a starting point. They need to be built into the readme, like needing to run `rush change` in my repo to create the logs of the changes that can be used to update the documentation. This should 100% be in the "contribution" area.

**Comment by webpro** [comment]
Closing this one as it's superseded by #348.
