### ISSUE TITLE
pactjs contract-generate --file 

### ISSUE THREAD

**Issue by advanztek** [kadena-community/kadena.js#189]
Hi, am trying to follow the pact election dapp tutorial which has been awesome (https://github.com/kadena-community/docs/blob/master/docs/build/guides/building-a-voting-dapp.md), but am having an issue with the frontend. 

pactjs contract-generate --file ../pact/election.pact; pactjs contract-generate --file ../pact/election-gas-station.pact; pactjs contract-generate --file ../pact/root/coin-v4.pact

The above command throws a syntax error
![Screenshot (10)](https://user-images.githubusercontent.com/70572531/224514149-e31bac17-bc8c-4b67-ae4a-55a0396f8bbf.png)

Any form of help would be appreciated.
thank you.

**Comment by javadkh2** [comment]
This issue has been addressed in the [windows compatibility PR](https://github.com/kadena-community/kadena.js/pull/294).

**Comment by alber70g** [comment]
I'll close this assuming this one is fixed in PR #294. If it's not please feel free to reopen.
