### ISSUE TITLE
Do not use generative algoritm to formulate answers

### ISSUE THREAD

**Issue by trendzetter** [kadena-community/kadena.js#590]
### Please confirm the following:

- [X] I have read the [Code of Conduct](https://github.com/kadena-community/kadena.js/blob/main/CODE_OF_CONDUCT.md)
- [X] The feature was not suggested before

### Is your feature request related to a problem?

Generative algorithms can and will produce incorrect answers. Especially regarding Kadena this seems to work very badly as shown in this tweet from a Kadena team member:
https://twitter.com/Randynamic_4/status/1659521551278956546 => all of the answer content generated is actually WRONG

Other development docs jumped on generative algoritms -"AI"- with problematic results.
reference: Mozilla Developer Network (MDN), one of the leading sources for developer documentation globally tried to introduce it and had to disable it again: https://www.theregister.com/2023/07/06/mozilla_ai_explain_shift/

### Describe the solution you'd like

Wait for the technology to mature for a longer time.

### Do you have any additional context?
Problematic feature "[Ask a question](https://github.com/kadena-community/kadena.js/blob/8a6888314d1b1174553d47e42f412251a4dfa80e/packages/apps/docs/src/components/SearchModal/SearchModal.tsx#L25)"

### Participation

- [X] I am willing to submit a pull request for this feature request.

**Comment by webpro** [comment]
Very valid concern, thanks for raising this. We need to tune and test things extensively, and when the results are not up to our standards we shouldn't use generated chat completions indeed.

**Comment by trendzetter** [comment]
As far as I can see the first version will lauch with semantic search and not generated answers. A safe choice imo

**Comment by trendzetter** [comment]
I still think its not worth the risk of generating incorrect answers -which will happen if it generates answers-. LLM can't distingish right from wrong. It just generates good looking text that often is in error. Plus, we have expert humans who can answer the questions correctly that at the same time help building a community link while visiting our socials such as discord.
Learning people the wrong things is lost time for everyone and it might become difficult to detect where it went wrong over time.
More about it: https://www.theregister.com/2023/08/07/chatgpt_stack_overflow_ai/

**Comment by trendzetter** [comment]
The QA feature is terrible and will point people the wrong way

**Comment by sstraatemans** [comment]
Yeah..its not great (yet)
we do have a big ALPHA warning there.
we want to gather some info about this. But if in the end it does not work, it will be removed.

Thanks for being on top of this.

**Comment by sstraatemans** [comment]
looking at different solutions as well
